# -*- coding: utf-8 -*-
"""Sistem Pakar Diagnosa

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1libjiCCX5uy-Qjn8A9QDJjnWIAtdhAos
"""

!pip install experta

!pip install --upgrade frozendict

from experta import *

class Diagnosis(KnowledgeEngine):
    @Rule(Fact(cough=True) & Fact(fever=True)& Fact(fatigue=True))
    def flu(self):
      print("diagnosis = anda flu")

    @Rule(Fact(cough=True) & Fact(fever=True)& Fact(breathing_difficulty=True))
    def pneumonia(self):
      print("diagnosis = anda pneumonia")

    @Rule(Fact(sneezing=True) & Fact(runny_nose=True)& Fact(cough=False))
    def covid(self):
      print("diagnosis = anda Pilek")

    @Rule(Fact(sore_throat=True) & Fact(fever=True))
    def throat_infection(self):
      print("diagnosis = anda infeksi tenggorokan")

    @Rule(Fact(cough=False) & Fact(fever=False)& Fact(fatigue=False))
    def healty(self):
      print("diagnosis = anda sehat")

    @Rule(Fact(cough=True) & Fact(breathing_difficulty=True))
    def healty(self):
      print("diagnosis = anda asma")



def get_input():
    """Helper function to get user input as boolean (yes/no)."""
    def ask_question(question):
      return input(question + "(yes/no):").strip().lower()=="yes"

    return {
      "cough": ask_question("Apakah anda batuk?"),
      "fever": ask_question("Apakah anda demam?"),
      "fatigue": ask_question("Apakah anda lelah?"),
      "breathing_difficulty": ask_question("Apakah anda kesulitan bernafas?"),
      "sneezing": ask_question("Apakah anda bersin?"),
      "runny_nose": ask_question("Apakah anda pilek?"),
      "sore_throat": ask_question("Apakah anda sakit tenggorokan?")
    }


if __name__ == "__main__":
  symptoms = get_input()
  engine = Diagnosis()
  engine.reset()

  for symptom,present in symptoms.items():
    engine.declare(Fact(**{symptom:present}))

  engine.run()