# -*- coding: utf-8 -*-
"""DFS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VfJ9HLRd-j94orXFqG0nXDihPeBMbhxM
"""

from collections import defaultdict

class graph:
  def __init__(self):
    self.graph = defaultdict(list)

  def addEdge(self, u, v):
    self.graph[u].append(v)

  def DFSUtil(self, v, visited):
    visited.add(v)
    print(v,end=' ')

    for neighbor in self.graph[v]:
      if neighbor not in visited:
        self.DFSUtil(neighbor,visited)

  def DFS(self, v):
    visited=set()
    self.DFSUtil(v, visited)

if __name__ == "__main__":
  g=graph()
  g.addEdge(0,1)
  g.addEdge(0,2)
  g.addEdge(1,2)
  g.addEdge(2,0)
  g.addEdge(2,3)
  g.addEdge(3,3)

  print("berikut adalah hasil penelusuran graf yang dimulai dari simpul 2:")
  g.DFS(0)